GET http://localhost:5268/games

###
GET http://localhost:5268/games/5

###
POST http://localhost:5268/games
Content-Type: application/json

{
    "name": "Final Fantasy XIV Dawn",
    "genre": "Platformer",
    "price": 59.99,
    "releaseDate": "2023-10-20"
}

###
PUT http://localhost:5268/games/1
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genre": "",
    "price": 9.99,
    "releaseDate": "1992-07-15"
}

###
DELETE http://localhost:5268/games/1
